// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIWv5CGxfD3aWA1mHBIMzKE6NfHPC1xTk',
    appId: '1:873699715559:android:2a903393aa2827c423f542',
    messagingSenderId: '873699715559',
    projectId: 'air-trip-app',
    storageBucket: 'air-trip-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwuY5tp_PUcZAIGJqJvdqBzlLHnWSoYcc',
    appId: '1:873699715559:ios:6b8d7fd2aad9b2ce23f542',
    messagingSenderId: '873699715559',
    projectId: 'air-trip-app',
    storageBucket: 'air-trip-app.firebasestorage.app',
    iosBundleId: 'com.jeffhearn.airtrip',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqeJsQ_9TWSwC2jyQ3-YK0OmUJv1mpiFo',
    appId: '1:873699715559:web:96a85484571a3cb123f542',
    messagingSenderId: '873699715559',
    projectId: 'air-trip-app',
    authDomain: 'air-trip-app.firebaseapp.com',
    storageBucket: 'air-trip-app.firebasestorage.app',
  );
}
