// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU9n9tnYsv7ulGlgelsYiLMheUOnH1vnw',
    appId: '1:240281914253:android:c93c0f94906ffd27228bc4',
    messagingSenderId: '240281914253',
    projectId: 'car-trip-app-8b71f',
    storageBucket: 'car-trip-app-8b71f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA99FO95HDaInrIW1eJ55PMlKeyz7rWjSw',
    appId: '1:240281914253:ios:bca8b4fd506f3afd228bc4',
    messagingSenderId: '240281914253',
    projectId: 'car-trip-app-8b71f',
    storageBucket: 'car-trip-app-8b71f.firebasestorage.app',
    iosBundleId: 'com.jeffhearn.cartrip',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNqYHjtz-YUT7RAHPsXamEQFLUkAEtAUs',
    appId: '1:240281914253:web:319863f439ee3f31228bc4',
    messagingSenderId: '240281914253',
    projectId: 'car-trip-app-8b71f',
    authDomain: 'car-trip-app-8b71f.firebaseapp.com',
    storageBucket: 'car-trip-app-8b71f.firebasestorage.app',
  );

}